sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ajaibs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ajaibs/docker-react npm run test

matrix:
  include:
    - dist: bionic
    - dist: xenial

